name: .NET Core

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore src/Calabonga.OperationResults.sln

      - name: Build the NuGet package
        run: dotnet build src/Calabonga.OperationResults.sln --configuration Release --output ${{env.DOTNET_ROOT}}\Package

      - name: Run Unit Tests
        run: dotnet test src/Calabonga.OperationResults.Tests/Calabonga.OperationResults.Tests.csproj

      - name: Publish NuGet Package OperationResultCore
        run: dotnet nuget push ${{env.DOTNET_ROOT}}\Package\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json










